### ISSUE TITLE
[Bug]: Crash while launching mc

### ISSUE THREAD

**Issue by LempekPL** [terrarium-earth/Cadmus#12]
### Bug Description

When I launch mc, after the minecraft window appears it crashes

### How to Reproduce?

1. Launch minecraft
2. Crash

### Expected Behavior

no crash

### Version

0.0.4

### Mod Loader Version

1.20.1 - 47.1.0

### Mod Loader

Forge

### Logs or additional context

https://mclo.gs/OmEmpYH

### Code of Conduct

- [X] I have searched the issue tracker and confirmed that the issue has not been reported
- [X] I have checked the FAQ (if one is present) and my issue is not listed
- [X] I have verified that I am using the latest version of the mod
- [X] I have verified that I have installed all the required dependencies for the mod
- [X] I have verified that I do not have Optifine installed. We will close issues if we detect Optifine is in your pack. We cannot fix Optifine issues. Please do not report issues with Optifine present.

**Comment by AlexNijjar** [comment]
Fixed in 0.0.5
