### ISSUE TITLE
[Bug]: Dispensers act as a dropper

### ISSUE THREAD

**Issue by CassieRoseZA** [terrarium-earth/Cadmus#13]
### Bug Description

When using a dispenser to place water or anything with the mod installed it acts like its a dropper
and its happening even in no claimed areas

### How to Reproduce?

1. Create New World
2. Get a dispenser and then get any thing that can be placed via a Dispenser (Water / Lava Bucket)
3. See it doesn't place it like expected and just drops the item

### Expected Behavior

For the Dispenser to Place the water

### Version

1.0.0

### Mod Loader Version

1.20.1 0.14.22

### Mod Loader

Fabric

### Logs or additional context

https://mclo.gs/7EADAoT

### Code of Conduct

- [X] I have searched the issue tracker and confirmed that the issue has not been reported
- [X] I have checked the FAQ (if one is present) and my issue is not listed
- [X] I have verified that I am using the latest version of the mod
- [X] I have verified that I have installed all the required dependencies for the mod
- [X] I have verified that I do not have Optifine installed. We will close issues if we detect Optifine is in your pack. We cannot fix Optifine issues. Please do not report issues with Optifine present.

**Comment by AlexNijjar** [comment]
Will be fixed in 1.0.1
