### ISSUE TITLE
[Feature Request]: A tag for blocks that may always be interacted with

### ISSUE THREAD

**Issue by Jamalam360** [terrarium-earth/Cadmus#15]
### Is your feature request related to a problem?

I would like to permanently whitelist gravestones block as usable in all claims 

### Solution(s)

A block tag that datapacks can add blocks to, for modpack creators

### Mod Version

N/A

### Mod Loader Version

1.20.1

### Mod Loader

Quilt

**Comment by Ant-Redstone** [comment]
Not only on server settings via datapacks, but get it configurable per player/claim would be perfect

So for example if a player wants to make a certain block interactible on their claim, like a specific chest (considering modded has plenty) or a specific pressure plate or button,

and maybe a second whitelist to allow breaking a certain block?

**Comment by AlexNijjar** [comment]
Added `allows_claim_interactions` as a block and entity tag. Any blocks/entities in these tags will always be intractable regardless if they're in a claim or not. Will look into the second suggestion.
