### ISSUE TITLE
[Bug]: Journey Map integration Broke

### ISSUE THREAD

**Issue by HavocStudio2** [terrarium-earth/Cadmus#17]
### Bug Description

Journey Map integration does not work atm
![image](https://github.com/terrarium-earth/Cadmus/assets/138988131/d4ecadcd-885b-4296-a549-2e6eb17b95b8)

![image](https://github.com/terrarium-earth/Cadmus/assets/138988131/bf951a69-abe8-4f7b-90dd-e59799d69fef)

### Version

Cadmus 1.0.0

### Mod Loader Version

47.1.3

### Code of Conduct

- [X] I have searched the issue tracker and confirmed that the issue has not been reported
- [X] I have checked the FAQ (if one is present) and my issue is not listed
- [X] I have verified that I am using the latest version of the mod
- [X] I have verified that I have installed all the required dependencies for the mod
- [X] I have verified that I do not have Optifine installed. We will close issues if we detect Optifine is in your pack. We cannot fix Optifine issues. Please do not report issues with Optifine present.

**Comment by ThatGravyBoat** [comment]
Did you turn on the integration in journeymap settings
