### ISSUE TITLE
[Feature Request]: Give Claim by VIA Command

### ISSUE THREAD

**Issue by HavocStudio2** [terrarium-earth/Cadmus#18]
### Is your feature request related to a problem?

Ability to set starter claim chunks and force chunks and the ability to add claim chunks & force chunks by command.

### Mod Version

Cadmus 1.0.0

### Mod Loader Version

47.1.3

**Comment by HavocStudio2** [comment]
![image](https://github.com/terrarium-earth/Cadmus/assets/138988131/4fafbacc-0185-47d4-9703-c8ad177a011b)

**Comment by HavocStudio2** [comment]
I see its a feature in [prometheus]

**Comment by AlexNijjar** [comment]
Yeah it's not really needed here because it's in prometheus already
