### ISSUE TITLE
[Feature Request]: permission nodes

### ISSUE THREAD

**Issue by HavocStudio2** [terrarium-earth/Cadmus#20]
### Is your feature request related to a problem?

I can't change the ammo of claims a player has without having the other mod prometheus installed I would like to suggest to have permission nodes for the claims.

### Solution(s)

cadmus.maxclaims: <number of claims allowed>
cadmus.chuunkclaims: <number of max chunk loads allowed>

### Mod Version

Latest 

### Mod Loader Version

1.20.1

**Comment by AlexNijjar** [comment]
You can without Prometheus; it's a game rule: `maxClaimedChunks` and `maxChunkLoaded`.

**Comment by HavocStudio2** [comment]
Why is it a gamerule and not permission 🤔

**Comment by CodexAdrian** [comment]
Implemented in 1.21
