### ISSUE TITLE
[Feature Request]: Support for Xaero's Map/Minimap

### ISSUE THREAD

**Issue by DarkkRevenant** [terrarium-earth/Cadmus#21]
### Is your feature request related to a problem?

It would be convenient to manage and view chunk claims using Xaero's Map/Minimap.

### Solution(s)

Include a method of claiming/unclaiming chunks as well as force loading/unload chunks directly into Xaero's Map. You could also see which chunks are claimed/unclaimed or loaded/unloaded on the map/minimap.

### Mod Version

N/A

### Mod Loader Version

N/A

### Mod Loader

Forge, Fabric, Quilt

**Comment by AlexNijjar** [comment]
There's an open PR for it (#6), but currently it's not done. You can use JourneyMap for now.

**Comment by Wolfy8198** [comment]
I saw in the pr that support was added for 1.21, is there any possibility it can be added for 1.20.1? I run a large modpack/server and it takes us a long time to update to newer minecraft versions because some of our core mods take a long time to update as well

**Comment by CodexAdrian** [comment]
Native support for Xaeros is implemented in 1.21
