### ISSUE TITLE
[Bug]: crashes, doesnt load

### ISSUE THREAD

**Issue by knoxhack** [terrarium-earth/Cadmus#22]
### Bug Description

crash, doesnt load

### How to Reproduce?

start game, crash

### Expected Behavior

load

### Version

cadmus-forge-1.20.1-1.0.2

### Mod Loader Version

1.20.1-Forge-47.1.3

### Mod Loader

Forge

### Logs or additional context

[https://gist.githubusercontent.com/knoxhack/9f80a2883dcbd53e21eea46e58ebf7e3/raw/f6e75ab1f95d62f1e5ba5ecce3d168ee883ecb46/cadmus](https://gist.githubusercontent.com/knoxhack/9f80a2883dcbd53e21eea46e58ebf7e3/raw/f6e75ab1f95d62f1e5ba5ecce3d168ee883ecb46/cadmus)

### Code of Conduct

- [X] I have searched the issue tracker and confirmed that the issue has not been reported
- [X] I have checked the FAQ (if one is present) and my issue is not listed
- [X] I have verified that I am using the latest version of the mod
- [X] I have verified that I have installed all the required dependencies for the mod
- [X] I have verified that I do not have Optifine installed. We will close issues if we detect Optifine is in your pack. We cannot fix Optifine issues. Please do not report issues with Optifine present.

**Comment by AlexNijjar** [comment]
update resourcefullib
