### ISSUE TITLE
[Bug]: Admin claims are cleared on server restart

### ISSUE THREAD

**Issue by charz185** [terrarium-earth/Cadmus#23]
### Bug Description

The mod clears all admin claims on server restart.

### How to Reproduce?

1. make a couple of admin claims
2. restart server
3. join back in and try to find existing admin claims

### Expected Behavior

The admin claims should continue existing after a server restart.

### Version

1.0.2

### Mod Loader Version

1.20.1 - 47.1.0

### Code of Conduct

- [X] I have searched the issue tracker and confirmed that the issue has not been reported
- [X] I have checked the FAQ (if one is present) and my issue is not listed
- [X] I have verified that I am using the latest version of the mod
- [X] I have verified that I have installed all the required dependencies for the mod
- [X] I have verified that I do not have Optifine installed. We will close issues if we detect Optifine is in your pack. We cannot fix Optifine issues. Please do not report issues with Optifine present.

**Comment by AlexNijjar** [comment]
I'm unable to reproduce this. I'm testing on forge 47.1.3 by making a fresh server instance with just Cadmus, creating a few admin claims, restarting the server, and finding that they're all still there. 

Can you try on a new server instance with just Cadmus? It may be old/corrupted files or another mod causing it.

**Comment by charz185** [comment]
Sorry for cluttering the issues tab. I tried it with a new instance, and now it is working. Thank you for your help.

**Comment by AlexNijjar** [comment]
👍
