### ISSUE TITLE
[Feature Request]: LuckPerms Support

### ISSUE THREAD

**Issue by LoboMetalurgico** [terrarium-earth/Cadmus#24]
### Is your feature request related to a problem?

I'm a developer for a network of servers and we use LuckPerms as our permission manager. It stores all the network settings synchronized across servers, and I believe that, like me, many other network admins and developers use LuckPerms. Therefore, adding support for LuckPerms would be a great addition.

### Solution(s)

Add Native Support to LuckPerms.

### Mod Version

1.0.2

### Mod Loader Version

1.20.1 - 0.14.22

### Mod Loader

Fabric

**Comment by samuelh2005** [comment]
For developers:

You may use https://github.com/lucko/fabric-permissions-api as a library to implement this support. It will also support other permissions mods that use it.

**Comment by CodexAdrian** [comment]
Cadmus now supports permissions with Prometheus, which integrates with Lucko's Permission API
