### ISSUE TITLE
[Bug]: the player loses the block when placing it if the protected area is not his

### ISSUE THREAD

**Issue by Misaass** [terrarium-earth/Cadmus#28]
### Bug Description

modify the mod in the blockPlace mixin to prevent that from happening, it would be a good feature since it should not remove the block from the player

```java
private void place(BlockPlaceContext blockPlaceContext, CallbackInfoReturnable<InteractionResult> cir) {


        if (!ClaimApi.API.canPlaceBlock(blockPlaceContext.getLevel(), blockPlaceContext.getClickedPos(), blockPlaceContext.getPlayer())) {

            Player playerPlaced = null;

            if(blockPlaceContext.getPlayer() != null) {
                playerPlaced = blockPlaceContext.getPlayer();

                int slot = playerPlaced.getInventory().selected;

                ItemStack stack = playerPlaced.getInventory().getItem(slot);

                cir.setReturnValue(InteractionResult.FAIL);

                blockPlaceContext.getPlayer().getInventory().setItem(slot, stack.copy());
            }
            else {
                cir.setReturnValue(InteractionResult.FAIL);
            }
        }
    }
```

### Version

1.0.0

### Mod Loader Version

1.20.x

### Mod Loader

Fabric

### Code of Conduct

- [X] I have searched the issue tracker and confirmed that the issue has not been reported
- [X] I have checked the FAQ (if one is present) and my issue is not listed
- [X] I have verified that I am using the latest version of the mod
- [X] I have verified that I have installed all the required dependencies for the mod
- [X] I have verified that I do not have Optifine installed. We will close issues if we detect Optifine is in your pack. We cannot fix Optifine issues. Please do not report issues with Optifine present.

**Comment by CodexAdrian** [comment]
The block isnt consumed in my testing, please verify it isnt a client desync issue
