### ISSUE TITLE
[Bug]: Bountiful Compatibility Issue

### ISSUE THREAD

**Issue by ItsCliffGaming** [terrarium-earth/Cadmus#29]
### Bug Description

When using Cadmus / Prometheus - if the Bounty Board is inside of a Claim it cannot be interacted with. Even with the flags for all interactions set to true (use true, use-chests true, block-interactions true, entity-interactions true, use-blocks true). When placed outside of a claim it works just fine, though.

### How to Reproduce?

Place a Bounty Board inside of an Admin Claim

### Expected Behavior

Bountiful should open like a chest GUI

### Version

1.0.2

### Mod Loader Version

0.14.23-1.20.1

### Mod Loader

Fabric

### Logs or additional context

Prometheus 1.2.1 // Bountiful v6.0.3+1.20.1

I submitted a but with Bountiful first, and this was the response I got:
https://github.com/ejektaflex/Bountiful/issues/255 

> This doesn't sound like Bountiful's problem to solve - Rather, if Cadmus is modifying game code to enforce claims, then it's their responsibility to make it work the way they intend. We're just using the basic interaction code that any other block entity would be using to open a GUI / turn in a bounty.
> 
> I would report this issue on their issue tracker instead:
> https://github.com/terrarium-earth/Cadmus/issues
> 
> If they have any advice for how I can handle my bounty board block interactions in a way that's easier for them to hook via Mixins (I assume that's how they do it), then I'm willing to change my code to do so, but as it stands this is a bug with Cadmus' implementation and not an inherent flaw with how Bountiful works.
> 
> Thanks for the report!

### Code of Conduct

- [X] I have searched the issue tracker and confirmed that the issue has not been reported
- [X] I have checked the FAQ (if one is present) and my issue is not listed
- [X] I have verified that I am using the latest version of the mod
- [X] I have verified that I have installed all the required dependencies for the mod
- [X] I have verified that I do not have Optifine installed. We will close issues if we detect Optifine is in your pack. We cannot fix Optifine issues. Please do not report issues with Optifine present.

**Comment by CodexAdrian** [comment]
Bountiful can add their blocks to the cadmus tags used to ignore certain blocks in claims. In addition to that, this issue i believe is resolved now that users can allow individual blocks to be bypassed in 1.21
