### ISSUE TITLE
[Feature Request]: External means obtaining data

### ISSUE THREAD

**Issue by superhealing** [terrarium-earth/Cadmus#3]
### Is your feature request related to a problem?

Hello, it is not related to a problem.

It would be nice to have the ability to obtain data through external means or make API requests. Essentially, a direct integration between mods, which would enable us to identify if a specific location has been reached or collect positions to back up a particular region instead of the entire world.

### Solution(s)

A proper way to extract data or give orders to the mod. For example, the example-mod could be instructed to unclaim the end portal until you have finished a quest. This would be useful for server-side usage, marketplace integration, or additional quests without interfering with the backend.

### Describe alternatives you've considered

One alternative I have considered is manually accessing the files saved by the mod and extracting data from there. However, this method is inefficient but could still work.

### Mod Version

0.0.0

### Mod Loader Version

1.20 - 0.14.21

### Mod Loader

Forge, Fabric

**Comment by CodexAdrian** [comment]
Cadmus has always had an API that could be used for this purpose. Its been expanded with more events in 1.21
