### ISSUE TITLE
[Bug]: Dispensers can't place shulker boxes

### ISSUE THREAD

**Issue by imagelesskink** [terrarium-earth/Cadmus#31]
### Bug Description

The latest version won't let dispensers place shulker boxes, even in unclaimed chunks.

### How to Reproduce?

1. Place dispenser
2. Insert shulker box
3. Activate dispenser

### Expected Behavior

The dispenser should place a shulker box

### Version

1.1.0

### Mod Loader Version

1.20.2 - 0.14.24

### Mod Loader

Fabric

### Logs or additional context

https://pastebin.com/fcjANdyX

### Code of Conduct

- [X] I have searched the issue tracker and confirmed that the issue has not been reported
- [X] I have checked the FAQ (if one is present) and my issue is not listed
- [X] I have verified that I am using the latest version of the mod
- [X] I have verified that I have installed all the required dependencies for the mod
- [X] I have verified that I do not have Optifine installed. We will close issues if we detect Optifine is in your pack. We cannot fix Optifine issues. Please do not report issues with Optifine present.

**Comment by AlexNijjar** [comment]
Fixed in 1508e0b
