### ISSUE TITLE
[Bug]: Gamerule doesn't change the values in server

### ISSUE THREAD

**Issue by Sirenize** [terrarium-earth/Cadmus#36]
### Bug Description

When trying to change the maxChunkLoaded and maxClaimedChunks gamerules in a server, the numbers do not update from the default values.

### Version

1.0.4

### Mod Loader Version

1.20.1 - 0.91.0

### Mod Loader

Fabric

### Code of Conduct

- [x] I have searched the issue tracker and confirmed that the issue has not been reported
- [X] I have checked the FAQ (if one is present) and my issue is not listed
- [X] I have verified that I am using the latest version of the mod
- [X] I have verified that I have installed all the required dependencies for the mod
- [X] I have verified that I do not have Optifine installed. We will close issues if we detect Optifine is in your pack. We cannot fix Optifine issues. Please do not report issues with Optifine present.

**Comment by AlexNijjar** [comment]
Do you have [Prometheus](https://modrinth.com/mod/prometheus) installed? Cadmus has support for prometheus and will automatically use the role system and ignore game rules when installed.

**Comment by AlexNijjar** [comment]
Closing as I'm assuming this is the issue and no response
