### ISSUE TITLE
[Bug]: Game crashes on second boot

### ISSUE THREAD

**Issue by Mrbysco** [terrarium-earth/Cadmus#38]
### Bug Description

The game fails to load the second time I boot it up complaining about a duplicate key

### How to Reproduce?

1. Install Cadmus on NeoForge 1.20.4
2. Start the game
3. Close the game
4. Start the game again
5. Crash

### Expected Behavior

I expect the game to launch the 2nd time without crashing

### Version

1.2.0

### Mod Loader Version

1.20.4 - 20.4.152-beta

### Mod Loader

NeoForge

### Logs or additional context

The error doesn't show up in the log as it happens too early
https://pastebin.com/6beH3JWt

### Code of Conduct

- [X] I have searched the issue tracker and confirmed that the issue has not been reported
- [X] I have checked the FAQ (if one is present) and my issue is not listed
- [X] I have verified that I am using the latest version of the mod
- [X] I have verified that I have installed all the required dependencies for the mod
- [X] I have verified that I do not have Optifine installed. We will close issues if we detect Optifine is in your pack. We cannot fix Optifine issues. Please do not report issues with Optifine present.

**Comment by Mrbysco** [comment]
To note, it's actually adding the keybind to the options.txt twice which is the issue

**Comment by AlexNijjar** [comment]
Published as `v1.2.1`. Do note that you may need to delete the duplicate `key.cadmus.open_claim_map` in your `options.txt` if you previously ran the game on 1.2.0.
