### ISSUE TITLE
[Feature Request]: please add option that entities can break and place in claimed land

### ISSUE THREAD

**Issue by CheryMarie** [terrarium-earth/Cadmus#39]
### Is your feature request related to a problem?

i wanted to use this with another mod where we can convert villagers and pay them to do chores for you like farming ect but they cant do anything on my claimed land 

### Solution(s)

in the (/claim settings) please add an option so entities that are not player can destroy and place blocks/plant seeds/cut trees ect?

### Describe alternatives you've considered

im not sure how else you would get this to work but anything you think of will do that will solve my issue x

### Mod Version

1.20.1-1.0.6

### Mod Loader Version

47.2.0

### Mod Loader

Forge

### Additional context

game version is 1.20.1

**Comment by CodexAdrian** [comment]
Added in 1.21
