### ISSUE TITLE
[Bug]: API not usable with Yarn mappings

### ISSUE THREAD

**Issue by Emafire003** [terrarium-earth/Cadmus#43]
### Bug Description

The java API for this mod is made with Mojmap mappings, but generally fabric utilises Yarn mappings. So the API, at least for fabric should support either something neutral, or yarn mappings. 
In particular, I can't use any of the methods from ClaimAPI or AdminClaimManager beacuse I would need to use ServerLevel, which in yarn is called ServerWorld. 

### Version

1.0.7

### Mod Loader Version

1.20.1 - 0.15.3

### Mod Loader

Fabric

### Code of Conduct

- [X] I have searched the issue tracker and confirmed that the issue has not been reported
- [X] I have checked the FAQ (if one is present) and my issue is not listed
- [X] I have verified that I am using the latest version of the mod
- [X] I have verified that I have installed all the required dependencies for the mod
- [X] I have verified that I do not have Optifine installed. We will close issues if we detect Optifine is in your pack. We cannot fix Optifine issues. Please do not report issues with Optifine present.

**Comment by CodexAdrian** [comment]
We cannot support different mappings on different platforms. We recommend switching to Official mappings or using a tiny remapper to remap the method that is failing in your development environment
