### ISSUE TITLE
[Bug]: all reagions reset on restart

### ISSUE THREAD

**Issue by ArcaneLegend1** [terrarium-earth/Cadmus#46]
### Bug Description

as title sais when server restarts all protections are gone

### How to Reproduce?

claim
restart
gone

### Version

1.0.7

### Mod Loader Version

47.2.20

### Mod Loader

Forge

### Code of Conduct

- [X] I have searched the issue tracker and confirmed that the issue has not been reported
- [X] I have checked the FAQ (if one is present) and my issue is not listed
- [X] I have verified that I am using the latest version of the mod
- [X] I have verified that I have installed all the required dependencies for the mod
- [X] I have verified that I do not have Optifine installed. We will close issues if we detect Optifine is in your pack. We cannot fix Optifine issues. Please do not report issues with Optifine present.

**Comment by CodexAdrian** [comment]
not enough information
