### ISSUE TITLE
[Feature Request]: Granular control over control groups per claim

### ISSUE THREAD

**Issue by Linguardium** [terrarium-earth/Cadmus#47]
### Is your feature request related to a problem?

Currently, pressure plates are either interactable with items on every claim, or on no claims. This removes any choice from players on how to protect their claim.

### Solution(s)

Provide a mechanism to allow group/tag creation and addition to configs, and then a mechanism for claim controls to be applied to those tags.

For example: datapacks create an entity tag "somemod:supermassive".  these entities should be able to trigger pressure plates but only if the claim owner allows it.  this tag can be added to a "pressurePlateInteraction" config group or tag. The claim owner now gets the option to enable pressure plate interactions from entities int he "somemod:supermassive" group.

### Describe alternatives you've considered

granular block by block allowances per-claim is also an option, and while more free, may become more cumbersome for players. Potentially a config similar to xaero minimap entity radar where entity groups can be created on the fly and configured might be an option.

### Mod Version

1.2.5-beta.3

### Mod Loader Version

N/A

### Mod Loader

Fabric

**Comment by CodexAdrian** [comment]
block by block granularity has been added in 1.21
