### ISSUE TITLE
[Feature Request]: Add a toggle to go into chunk claiming mode

### ISSUE THREAD

**Issue by stantios** [terrarium-earth/Cadmus#5]
### Is your feature request related to a problem?

No

### Solution(s)

I would like a feature where cadmus can be toggled with a button on the side. I think the best way to describe this is an image from the [JourneyMap Intergration](https://modrinth.com/mod/journeymap-integration) mod where they have a button on the right side to go into a chunk claiming mode and an indicator on the bottom left to see how many chunks are claimed and the amount of chunks force loaded.

This GIF is from the [JourneyMap Intergration](https://modrinth.com/mod/journeymap-integration) mod description: https://i.imgur.com/Ni9fQoo.gif

### Describe alternatives you've considered

I have not really considered any alternatives at the moment.

### Mod Version

0.0.0

### Mod Loader Version

1.20 - 0.14.21

### Mod Loader

Fabric

### Additional context

None

**Comment by CodexAdrian** [comment]
JourneyMap Integration has been added
