### ISSUE TITLE
[Bug]: Strange data files bugs

### ISSUE THREAD

**Issue by Proxwian** [terrarium-earth/Cadmus#51]
### Bug Description

With files from 1st archive in world data folder, chunk count from Prometheus roles doesn't sync with Cadmus

With files from 2nd archive, Prometheus claims count sync works, but Argonauts claims doesn't work, players can't claim chunks as Guild

### How to Reproduce?

1. Copy files from first archive and try to change @everything role claim count
2. Copy files from 2nd archive and try to claim any chunk with Argonauts Guild (it claims as player)

### Version

1.0.8

### Mod Loader Version

1.20.1 - 47.2.23

### Mod Loader

Forge

### Logs or additional context

[cadmus_new.zip](https://github.com/terrarium-earth/Cadmus/files/15059294/cadmus_new.zip)
[cadmus_old.zip](https://github.com/terrarium-earth/Cadmus/files/15059295/cadmus_old.zip)

### Code of Conduct

- [X] I have searched the issue tracker and confirmed that the issue has not been reported
- [X] I have checked the FAQ (if one is present) and my issue is not listed
- [X] I have verified that I am using the latest version of the mod
- [X] I have verified that I have installed all the required dependencies for the mod
- [X] I have verified that I do not have Optifine installed. We will close issues if we detect Optifine is in your pack. We cannot fix Optifine issues. Please do not report issues with Optifine present.

**Comment by CodexAdrian** [comment]
this issue is largely solved in 1.21, but basically this was an issue due to how the "team selection" system for claims worked, which has been overhauled in 1.21 to be easier to use
