### ISSUE TITLE
[Feature Request]: Bump version to 1.20.6

### ISSUE THREAD

**Issue by Clumsius** [terrarium-earth/Cadmus#55]
### Is your feature request related to a problem?

I'm always frustrated when "The mod isn't updated to latest Minecraft versions" happens.

### Solution(s)

When "It is updated" happens "Me and the boys on latest versions can vibe without staying downgraded" should happen like this other thing when "Cadmus updated = cool" happens.

### Describe alternatives you've considered

Maybe "If you updated" could also do "More happy users, not just me" when "Update" happens instead of "Staying downgraded" doing something when "Downgraded" happens.

### Mod Version

1.2.2

### Mod Loader Version

1.20.4

### Mod Loader

Fabric

### Additional context

Please update to Minecraft Fabric 1.20.6, I would like my server to stay safe and updated! :D

**Comment by CodexAdrian** [comment]
Cadmus will not support 1.20.6, a 1.21 version will be released soon
