### ISSUE TITLE
[Feature Request]: Zoom/Pan on built-in claim map

### ISSUE THREAD

**Issue by akoimeexx** [terrarium-earth/Cadmus#58]
### Is your feature request related to a problem?

When using the claim map to mark out regions for community usage, I am unable to navigate around the claim map from within the UI and have to exit it, move to another area, and re-enter the map in sections to properly claim areas.

### Solution(s)

Using keyboard arrow keys or WASD controls while in the claim map to allow panning the map around to facilitate easier claiming without having to repeatedly exit and re-enter the UI.

### Mod Version

1.0.8

### Mod Loader Version

1.20.1-0.16.3

### Mod Loader

Fabric

**Comment by CodexAdrian** [comment]
This wont be implemented in the cadmus map. If you'd like this kind of functionality, please use the integration Cadmus has with JourneyMap or Xaeros World Map

**Comment by akoimeexx** [comment]
That seems unfortunate; I generally don't add in Journey or Xaeros, as I try to run my mod packs light enough to work on a variety of machines for my local Minecraft server.

Can I take this to mean that eventually Cadmus won't bother with a map at all, if we need to depend on utilizing additional world map mods?

**Comment by CodexAdrian** [comment]
A minimap is out of scope for cadmus, as our in game map is very simple and will only render the blocks the player has loaded into the world. it does not actually cache the blocks the player sees on their travels, which is what would be required to achieve this kind of zooming feature. 

Generally speaking i agree that the existing solutions for world maps arent great on performance. But i dont think us taking a crack at making one for cadmus just for this feature would fair better considering that its not really a goal of the mod so we wouldnt be able to dedicate the care and attention needed to make it a good map. 

Id recommend using JourneyMap or Xaeros though, while they arent perfect they aren't so heavy that they would impact most users. you could ship JourneyMap and have the minimap portion disabled by default. JourneyMap is more efficient with memory and having the minimap off should make it not affect users FPS so this would be the easiest way to keep your pack light while giving users this functionality.
