### ISSUE TITLE
[Feature Request]: Possible way to add Waystones compatibility?

### ISSUE THREAD

**Issue by Wolfy8198** [terrarium-earth/Cadmus#61]
### Is your feature request related to a problem?

I added Cadmus to my server's modpack as a way to protect the ME system from AE2 after the removal of the Security Terminal, but it was brought to my attention that players can't activate other player's waystones anymore, or use them to get to their own base. 

### Solution(s)

Could you add a config option for blocks that bypass claims or something like that? A config in general would be nice, too.

### Mod Version

1.0.8

### Mod Loader Version

1.20.1

### Mod Loader

Fabric

**Comment by CodexAdrian** [comment]
This is implemented in 1.21

**Comment by Wolfy8198** [comment]
Is there any possibility that those can be added to 1.20.1? A lot of the
mods we use aren't available for 1.20.1 yet, and some of them have changed
to a different modloader, so we won't be able to update for a while. Plus
Season 3 just started a couple of months ago, so I can't end it now to
update anyways.

**Comment by CodexAdrian** [comment]
No im afraid, this feature was added as a part of the cadmus rewrite in 1.21. nothing is being backported
