### ISSUE TITLE
[Feature Request]: Journeymap Integration

### ISSUE THREAD

**Issue by cl0ck-byte** [terrarium-earth/Cadmus#8]
### Is your feature request related to a problem?

Considering that there's no worldmap/minimap solution from Terrarium _yet_, it'd be neat to have [JourneyMap](https://github.com/TeamJM/journeymap) integration within Cadmus, similarly to what was done with [FTBChunks](https://github.com/frank89722/JourneyMapIntegration)

### Solution(s)

- Allow JM to claim/unclaim chunks
- Display chunks claimed by players in JM
- Show claimed chunks count and claim limits

### Describe alternatives you've considered

Create yet another minimap/worldmap mod?

### Mod Version

Irrevelant

### Mod Loader Version

Irrevelant

### Mod Loader

N/A

**Comment by ThatGravyBoat** [comment]
We already have integration made and the rest will be made when #5 is added
